### ISSUE TITLE
filterObjects, rejectObjects

### ISSUE THREAD

**Issue by mathisonian** [robb/Underscore.m#49]
From reading the documentation on http://underscorem.org/, methods such as `filterObjects` and `rejectObjects` seem to be available, but these are not in my cocoapods installation, and I can't find a reference to them in the code.

Do such methods still exist?

**Comment by ipetkov** [comment]
Yep! You can either use [`Underscore.filterKeys`](https://github.com/robb/Underscore.m/blob/master/Underscore/Underscore%2BFunctional.m#L234) for example, or use a [dictionary wrapper](https://github.com/robb/Underscore.m/blob/master/Underscore/USDictionaryWrapper.m#L156), or their `NSArray` equivalents.

These functions should be available since the initial release so even an older version of the pod should include them. Did you get any compiler errors that they were undefined?

**Comment by mathisonian** [comment]
Thanks for the quick response!

I think the confusion came because the documentation on [underscorem.org](http://underscorem.org) showed the method as being called `filterObjects`, `rejectObjects`, but I see in the link you gave they are actually named `filterValues` and `rejectValues`. 

I will submit a PR to update those docs
